services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - 'MARIADB_DATABASE=mydatabase'
#      - 'MARIADB_PASSWORD=secret'
#      - 'MARIADB_ROOT_PASSWORD=verysecret'
#      - 'MARIADB_USER=myuser'
#    ports:
#      - '3306'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'